model_type: "mlp"
batch_size: 512
learning_rate: 0.001
epochs: 50
embedding_dim: 512

compiler:
  use_tree: false

vision:
  use_clip: false

dataset:
  name: "mscoco"
  class: "modules.data_pipeline.datasets.CocoDataset"
  collate_fn: "modules.data_pipeline.datasets.coco_collate_fn"
  eval_mapper: "modules.models.fusion.engine.mscoco_mapper"

splits:
  train:
    text_path: "data/mscoco/processed/train.pkl"
    img_path: "data/mscoco/raw/images/train2017.zip"
  val:
    text_path: "data/mscoco/processed/validation.pkl"
    img_path: "data/mscoco/raw/images/val2017.zip"

evaluation_tasks:
  - "global_retrieval"