model_type: "vqc"
batch_size: 256
learning_rate: 0.001
epochs: 100
embedding_qubits: 9

compiler:
  ansatz: "custom_v5"
  n: 3
  s: 3
  p: 3
  layers: 3
  curry = true

vision:
  layers: 3
  use_clip: false

dataset:
  name: "svo-probes"
  class: "modules.data_pipeline.datasets.SVODataset"
  collate_fn: "modules.data_pipeline.datasets.svo_collate_fn"
  eval_mapper: "modules.models.fusion.engine.svo_mapper"

splits:
  train:
    text_path: "data/svo-probes/processed/train.pkl"
    img_path: "data/svo-probes/processed/image_embeddings.pt"
  val:
    text_path: "data/svo-probes/processed/val.pkl"
    img_path: "data/svo-probes/processed/image_embeddings.pt"

evaluation_tasks:
  - "evaluate_image_choice"